version: "3"
services:
  proxy:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
  onewebsite:
    restart: always
    build: .
    volumes:
      - ./src/main/resources/application.yml:/usr/local/lib/application.yml
      - ./magic-scripts:/opt/metadata/magic-api
      - ./attachments:/opt/erupt-attachment
    ports:
      - 8080:8080
    

