version: "3"
services:
  onewebsite:
    restart: always
    build: .
    volumes:
      - ./src/main/resources/application.yml:/usr/local/lib/application.yml
      - ./magic-scripts:/opt/metadata/magic-api
      - ./attachments:/opt/erupt-attachment
    ports:
      - 8080:8080
    

