server:
  port: 9999
magic-api:
  #??web????
  web: /
  resource:
    location: ${MAGIC_LOCATION_PATH}
  show-url: false
  show-sql: true #????SQL
  response-code:
    success: 0 #?????code?
    invalid: 1 #????????code?
    exception: -1 #???????code?
  page:
    size: pageSize # ?????????? ????size
    page: page # ????????? ????page
    default-page: 1 # ??????? ????1
    default-size: 10 # ????????? ????10


spring:
  datasource:
    url: ${MYSQL_EN_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=${MYSQL_EN_TZ}
    username: ${MYSQL_EN_USERNAME}
    password: ${MYSQL_EN_PASSWORD}