erupt-app:
  verifyCodeCount: 2
  pwdTransferEncrypt: true
  locales: [ "zh-CN", "en-US"]
erupt:
  csrfInspect: true
  redisSession: false
  uploadPath: /Users/rivery/Desktop/projects/new-website/attachments
  keepUploadFileName: false
  upms.expireTimeByLogin: 60
  job.enable: true
  security.recordOperateLog: true
magic-api:
  web: /magic/web
  resource.location: /Users/rivery/Desktop/projects/new-website/magic-scripts
  show-url: false
  page:
    size: pageSize # 页大小的请求参数名称 缺省时为size
    page: page # 页码的请求参数名称 缺省时为page
    default-page: 1 # 自定义默认首页 缺省时为1
    default-size: 10 # 自定义为默认页大小 缺省时为10
spring:
  datasource:
    url: jdbc:mysql://192.168.8.44:3306/website?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: nebula
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS